version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
    volumes:
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - api.quantumcx.com
          - auth.quantumcx.com
          - ws.slanger.quantumcx.com
          - api.slanger.quantumcx.com
          - pma.quantumcx.com
          - eth.quantumcx.com
          - monitor.quantumcx.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.quantumcx.com'
      traefik.port: 8080
